{ fetchNuGet }: [
  (fetchNuGet { pname = "Microsoft.AspNetCore.OpenApi"; version = "9.0.8"; hash = "sha256-iMkEvwy/j2Snc7pJbHu+eaVsTRHCIvleWdZZY5JAR1w="; })
  (fetchNuGet { pname = "Microsoft.Data.Sqlite.Core"; version = "9.0.11"; hash = "sha256-cz4FkzDDKEINNzVWLt3j8nbi5kKzs2dbbbqF1uGnTzA="; })
  (fetchNuGet { pname = "Microsoft.EntityFrameworkCore"; version = "9.0.11"; hash = "sha256-c5RiSd/QPerOYUueN8G4wcmJG8/TmOiJniYI9gf2j8Q="; })
  (fetchNuGet { pname = "Microsoft.EntityFrameworkCore.Abstractions"; version = "9.0.11"; hash = "sha256-60/92aSe/qZcKqDOTf8uNBXea6/lqrjW2WnFSdvCTdk="; })
  (fetchNuGet { pname = "Microsoft.EntityFrameworkCore.Analyzers"; version = "9.0.11"; hash = "sha256-hAiDz5WksFapSdV3N4Db7zAH7M+sBvEiO4I1BmQu+MY="; })
  (fetchNuGet { pname = "Microsoft.EntityFrameworkCore.Relational"; version = "9.0.11"; hash = "sha256-mqsnHzVpFTlVyd/vLqAuM8Js0Q7CBJN2K8iYKmq/VXY="; })
  (fetchNuGet { pname = "Microsoft.EntityFrameworkCore.Sqlite"; version = "9.0.11"; hash = "sha256-IMbQVABUUIox18jABD75ywKXqb4K1BE69TEhkYYCqGc="; })
  (fetchNuGet { pname = "Microsoft.EntityFrameworkCore.Sqlite.Core"; version = "9.0.11"; hash = "sha256-o6yLDDyptXAvwTwMjhe6KLRfYqvh64OWhwABNa47UDU="; })
  (fetchNuGet { pname = "Microsoft.Extensions.Caching.Abstractions"; version = "9.0.11"; hash = "sha256-+1PEeH8he6Yk0r/6UpQ69ej38vYtuVyS4JJdKEkrheQ="; })
  (fetchNuGet { pname = "Microsoft.Extensions.Caching.Memory"; version = "9.0.11"; hash = "sha256-/ZHjoBvGkq5a6kNvqBTkz5JfBOu1zLFbuTMBsPXUYwY="; })
  (fetchNuGet { pname = "Microsoft.Extensions.Configuration.Abstractions"; version = "9.0.11"; hash = "sha256-bBvR5XeJpoim/4JUsDtp+z7GU2vx37NwjAjeXLc+Ycg="; })
  (fetchNuGet { pname = "Microsoft.Extensions.DependencyInjection"; version = "9.0.11"; hash = "sha256-A77to45DYqDT5vCHAa2RBqTVOKND1KdYTX3PCTd2shA="; })
  (fetchNuGet { pname = "Microsoft.Extensions.DependencyInjection.Abstractions"; version = "9.0.11"; hash = "sha256-7ybl+oJ7NkkOX3Ns7KAgaHy3CP2LvI1VBTJ9WbMIYC0="; })
  (fetchNuGet { pname = "Microsoft.Extensions.DependencyModel"; version = "9.0.11"; hash = "sha256-nKxWogDgMM/JqgqEP0vfNOfjrPB/KWcyr5V1UnCZaac="; })
  (fetchNuGet { pname = "Microsoft.Extensions.Logging"; version = "9.0.11"; hash = "sha256-AGNOGjQ1xEM3ct5iM21TeaJ/zdLtt+UduTUUs5WQi1E="; })
  (fetchNuGet { pname = "Microsoft.Extensions.Logging.Abstractions"; version = "9.0.11"; hash = "sha256-hk1zL4wTkoix+681q7MC/B9VLThibu4L01Pj6ZtNy14="; })
  (fetchNuGet { pname = "Microsoft.Extensions.Options"; version = "9.0.11"; hash = "sha256-e7yi+sje07SUUxbZ6+ZjvcFMgUtpLZ8vz1KdPinF310="; })
  (fetchNuGet { pname = "Microsoft.Extensions.Primitives"; version = "9.0.11"; hash = "sha256-T1t0dsPVxP0TrmXfPXsA+wZKgS7TecZXvRS261G+KY8="; })
  (fetchNuGet { pname = "Microsoft.OpenApi"; version = "1.6.17"; hash = "sha256-Wx9PwlEJPNMq1kp59nJJnLHQ+yNhqCTudcokmlP+tSk="; })
  (fetchNuGet { pname = "SQLitePCLRaw.bundle_e_sqlite3"; version = "2.1.10"; hash = "sha256-kZIWjH/TVTXRIsHPZSl7zoC4KAMBMWmgFYGLrQ15Occ="; })
  (fetchNuGet { pname = "SQLitePCLRaw.core"; version = "2.1.10"; hash = "sha256-gpZcYwiJVCVwCyJu0R6hYxyMB39VhJDmYh9LxcIVAA8="; })
  (fetchNuGet { pname = "SQLitePCLRaw.lib.e_sqlite3"; version = "2.1.10"; hash = "sha256-m2v2RQWol+1MNGZsx+G2N++T9BNtQGLLHXUjcwkdCnc="; })
  (fetchNuGet { pname = "SQLitePCLRaw.provider.e_sqlite3"; version = "2.1.10"; hash = "sha256-MLs3jiETLZ7k/TgkHynZegCWuAbgHaDQKTPB0iNv7Fg="; })
  (fetchNuGet { pname = "System.Memory"; version = "4.5.3"; hash = "sha256-Cvl7RbRbRu9qKzeRBWjavUkseT2jhZBUWV1SPipUWFk="; })
  (fetchNuGet { pname = "System.Text.Json"; version = "9.0.11"; hash = "sha256-eufG191lCpSBB471mXeOU/Osp1WAUZvCq+DoB+q9dyU="; })
]
